# Generated by Django 4.2.6 on 2023-10-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
