# Generated by Django 4.2.6 on 2023-12-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
