# Generated by Django 4.2.6 on 2024-01-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_pricelist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('ItemImage', models.ImageField(upload_to='ItemImage/')),
            ],
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
