# Generated by Django 4.2.6 on 2024-01-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_itemlist_delete_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=6)),
                ('houseName', models.CharField(max_length=100)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
