# Generated by Django 4.2.6 on 2024-01-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_orders_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(max_length=10)),
                ('customerId', models.IntegerField(max_length=10)),
                ('date_time', models.IntegerField(max_length=40)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.status')),
            ],
        ),
    ]
