# Generated by Django 4.2.6 on 2024-01-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_status_customerordertracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerordertracker',
            name='date_time',
            field=models.CharField(max_length=40),
        ),
    ]
