# Generated by Django 4.2.6 on 2024-01-22 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_customerordertracker_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('houseName', models.CharField(max_length=100)),
                ('customerId', models.IntegerField()),
                ('dateTime', models.CharField(max_length=40)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.status')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.DeleteModel(
            name='CustomerOrderTracker',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
